export type RecipeTag = "quick" | "veg" | "global" | "new" | "dessert" | "snack" | "salad" | "soup" | "breakfast";

export interface Recipe {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  photo: string;           // Unsplash photo ID (legacy curated recipes)
  imageUrl?: string;       // Full image URL (TheMealDB-imported recipes)
  youtubeId: string;       // YouTube video ID to embed
  youtubeTitle: string;    // Channel / video title for attribution
  tags: RecipeTag[];
  region?: string;
  minutes: number;
  rating: number;
  servings: number;
  calories: number;
  ingredients: { qty: string; name: string }[];
  steps: string[];
  description?: string;
  source?: string;         // Original recipe URL (for attribution)
}

/** Returns the best image URL for a recipe — prefers imageUrl, falls back to
 *  the Unsplash CDN constructed from the legacy `photo` ID. */
export function recipeImage(r: Recipe, width = 600): string {
  if (r.imageUrl) return r.imageUrl;
  if (r.photo) return `https://images.unsplash.com/${r.photo}?w=${width}&q=80&fit=crop`;
  return "";
}

export const recipes: Recipe[] = [
  /* ─────────────────────── QUICK / VEG ─────────────────────── */
  {
    id: "pasta-pomodoro",
    name: "Pasta al Pomodoro",
    emoji: "🍝",
    gradient: "linear-gradient(135deg, oklch(82% 0.09 40), oklch(76% 0.14 75))",
    photo: "photo-1621996346565-e3dbc646d9a9",
    youtubeId: "g5SLToGiDd0",
    youtubeTitle: "The Secret Behind My Most Famous Pasta Recipe",
    tags: ["quick", "veg"],
    minutes: 20,
    rating: 4.9,
    servings: 2,
    calories: 420,
    description: "A weeknight classic — deeply flavoured, incredibly simple. Just five ingredients and twenty minutes.",
    ingredients: [
      { qty: "200g", name: "Spaghetti" },
      { qty: "400g", name: "Cherry tomatoes" },
      { qty: "3 cloves", name: "Garlic" },
      { qty: "3 tbsp", name: "Olive oil, extra virgin" },
      { qty: "handful", name: "Fresh basil leaves" },
    ],
    steps: [
      "Boil salted water and cook spaghetti until al dente, about 8 minutes. Reserve ½ cup pasta water.",
      "Meanwhile, heat olive oil in a wide pan. Add sliced garlic and cook 1 minute until fragrant.",
      "Add halved cherry tomatoes. Cook over medium-high, crushing gently, until jammy — about 8 minutes.",
      "Toss drained pasta into sauce, adding pasta water to loosen. Tear in basil and serve immediately.",
    ],
  },
  {
    id: "shakshuka",
    name: "Shakshuka",
    emoji: "🥘",
    gradient: "linear-gradient(135deg, oklch(90% 0.07 78), oklch(76% 0.14 75))",
    photo: "photo-1590412200988-a436970781fa",
    youtubeId: "SjCkW-oAFQ8",
    youtubeTitle: "Shakshuka | Basics with Babish",
    tags: ["quick"],
    minutes: 18,
    rating: 4.7,
    servings: 2,
    calories: 380,
    description: "Eggs poached directly in a spiced tomato sauce — a one-pan wonder from North Africa and the Middle East.",
    ingredients: [
      { qty: "4", name: "Eggs" },
      { qty: "400g", name: "Crushed tomatoes" },
      { qty: "1", name: "Red bell pepper" },
      { qty: "1 tsp", name: "Smoked paprika" },
      { qty: "1 tsp", name: "Cumin" },
    ],
    steps: [
      "Sauté diced pepper and onion in olive oil until soft.",
      "Stir in spices, then crushed tomatoes. Simmer 8 minutes.",
      "Crack eggs into wells in the sauce. Cover and cook 5 minutes until set.",
      "Top with parsley and serve with crusty bread.",
    ],
  },
  {
    id: "avocado-toast",
    name: "Avocado Toast",
    emoji: "🥑",
    gradient: "linear-gradient(135deg, oklch(88% 0.07 145), oklch(70% 0.12 145))",
    photo: "photo-1541519227354-08fa5d50c44d",
    youtubeId: "Wmo1NoYEFPw",
    youtubeTitle: "Gordon Ramsay's Avocado Toast",
    tags: ["quick", "veg", "breakfast"],
    minutes: 10,
    rating: 4.5,
    servings: 1,
    calories: 280,
    description: "The classic made properly — creamy avocado on perfectly toasted bread with a finishing touch of chilli and lemon.",
    ingredients: [
      { qty: "1 ripe", name: "Avocado" },
      { qty: "2 slices", name: "Sourdough bread" },
      { qty: "½", name: "Lemon, juiced" },
      { qty: "pinch", name: "Chilli flakes" },
      { qty: "to taste", name: "Salt & black pepper" },
    ],
    steps: [
      "Toast sourdough until golden and crisp.",
      "Halve avocado, remove stone, scoop into bowl.",
      "Mash with lemon juice, salt, and pepper. Keep it slightly chunky.",
      "Spread generously on toast. Finish with chilli flakes and a drizzle of good olive oil.",
    ],
  },
  {
    id: "grain-bowl",
    name: "Warm Grain Bowl",
    emoji: "🥗",
    gradient: "linear-gradient(135deg, oklch(88% 0.05 145), oklch(64% 0.08 145))",
    photo: "photo-1512621776951-a57141f2eefd",
    youtubeId: "4PnK3ij50DY",
    youtubeTitle: "Farro Grain Bowl Recipe",
    tags: ["veg", "salad"],
    minutes: 15,
    rating: 4.8,
    servings: 2,
    calories: 510,
    description: "Nutty grains, roasted sweet potato, and a creamy tahini dressing. Wholesome and endlessly riffable.",
    ingredients: [
      { qty: "1 cup", name: "Farro or quinoa" },
      { qty: "1", name: "Roasted sweet potato" },
      { qty: "1 cup", name: "Baby spinach" },
      { qty: "2 tbsp", name: "Tahini" },
      { qty: "1 tbsp", name: "Lemon juice" },
    ],
    steps: [
      "Cook grain per package instructions.",
      "Whisk tahini with lemon juice and a splash of water to a pourable dressing.",
      "Pile grain, sweet potato, and spinach in bowls.",
      "Drizzle with dressing and finish with flaky salt.",
    ],
  },

  /* ─────────────────────── GLOBAL MAINS ───────────────────── */
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    emoji: "🍛",
    gradient: "linear-gradient(135deg, oklch(86% 0.09 55), oklch(68% 0.15 45))",
    photo: "photo-1603894584373-5ac82b2ae398",
    youtubeId: "vjKEUBg-ziY",
    youtubeTitle: "The BEST Butter Chicken",
    tags: ["global"],
    region: "India",
    minutes: 40,
    rating: 4.9,
    servings: 4,
    calories: 580,
    description: "Tender chicken in a silky, aromatic tomato-cream sauce — the dish that made Indian food famous worldwide.",
    ingredients: [
      { qty: "600g", name: "Chicken thighs, diced" },
      { qty: "400g", name: "Crushed tomatoes" },
      { qty: "200ml", name: "Double cream" },
      { qty: "3 tbsp", name: "Butter" },
      { qty: "1 tbsp", name: "Garam masala" },
      { qty: "1 tsp", name: "Ground ginger" },
    ],
    steps: [
      "Marinate chicken in yogurt, garam masala and ginger for 30 min. Sear in a hot pan until golden.",
      "In the same pan, melt butter and fry onion until soft. Add garlic and spices — cook 1 minute.",
      "Pour in crushed tomatoes and simmer 15 minutes until thick.",
      "Blend sauce until smooth. Return chicken, add cream, simmer 5 minutes. Serve with naan.",
    ],
  },
  {
    id: "beef-ramen",
    name: "Beef Ramen",
    emoji: "🍜",
    gradient: "linear-gradient(135deg, oklch(35% 0.04 60), oklch(55% 0.08 50))",
    photo: "photo-1565628308934-c731959645f2",
    youtubeId: "R1wQIPqnpEY",
    youtubeTitle: "One-Pot Beef Ramen Soup",
    tags: ["global"],
    region: "Japan",
    minutes: 50,
    rating: 4.8,
    servings: 2,
    calories: 680,
    description: "A deeply savoury broth with silky ramen noodles, tender beef and a soft-boiled egg. Comfort in a bowl.",
    ingredients: [
      { qty: "300g", name: "Beef sirloin, thinly sliced" },
      { qty: "2 portions", name: "Ramen noodles" },
      { qty: "1L", name: "Beef stock" },
      { qty: "3 tbsp", name: "Soy sauce" },
      { qty: "1 tbsp", name: "Miso paste" },
      { qty: "2", name: "Soft-boiled eggs" },
    ],
    steps: [
      "Bring stock to a simmer. Stir in soy sauce, miso, and a dash of sesame oil.",
      "Cook noodles according to package and divide into bowls.",
      "Sear beef slices in a hot pan for 30 seconds per side — keep them pink.",
      "Ladle broth over noodles, top with beef, halved egg, spring onion, and nori.",
    ],
  },
  {
    id: "fish-tacos",
    name: "Baja Fish Tacos",
    emoji: "🌮",
    gradient: "linear-gradient(135deg, oklch(80% 0.07 195), oklch(58% 0.10 195))",
    photo: "photo-1551504734-5ee1c4a1479b",
    youtubeId: "ZSWBwvW4RE4",
    youtubeTitle: "How to Make Baja Style Fish Tacos | Food Network",
    tags: ["global"],
    region: "Latam",
    minutes: 30,
    rating: 4.6,
    servings: 2,
    calories: 540,
    description: "Crispy white fish, tangy lime crema, and crunchy slaw in warm corn tortillas — the perfect taco.",
    ingredients: [
      { qty: "300g", name: "White fish fillet" },
      { qty: "6", name: "Corn tortillas" },
      { qty: "1 cup", name: "Shredded cabbage" },
      { qty: "2 tbsp", name: "Lime crema" },
      { qty: "1", name: "Lime, wedged" },
    ],
    steps: [
      "Season fish with chili and salt; sear 3 minutes per side.",
      "Warm tortillas in a dry pan.",
      "Flake fish and divide between tortillas.",
      "Top with cabbage, crema, and a squeeze of lime.",
    ],
  },
  {
    id: "shrimp-pasta",
    name: "Lemon Garlic Shrimp Pasta",
    emoji: "🍤",
    gradient: "linear-gradient(135deg, oklch(92% 0.05 85), oklch(72% 0.10 195))",
    photo: "photo-1563379926898-05f4575a45d8",
    youtubeId: "RMzZ3Kjnusc",
    youtubeTitle: "Lemon Garlic Shrimp Pasta — So Easy You'll Make It All Year",
    tags: ["quick"],
    minutes: 20,
    rating: 4.7,
    servings: 2,
    calories: 490,
    description: "Plump shrimp tossed with linguine in a bright, garlicky lemon butter sauce. Twenty minutes start to finish.",
    ingredients: [
      { qty: "250g", name: "Linguine" },
      { qty: "300g", name: "Large shrimp, peeled" },
      { qty: "4 cloves", name: "Garlic, sliced" },
      { qty: "1", name: "Lemon, zest & juice" },
      { qty: "2 tbsp", name: "Butter" },
      { qty: "handful", name: "Parsley, chopped" },
    ],
    steps: [
      "Cook pasta in salted water. Reserve 1 cup pasta water.",
      "Sauté garlic in butter 1 minute. Add shrimp, cook 2 min per side until pink.",
      "Add lemon zest and juice. Toss in drained pasta with a splash of pasta water.",
      "Finish with parsley and black pepper. Serve immediately.",
    ],
  },
  {
    id: "thai-basil",
    name: "Thai Basil Stir-fry",
    emoji: "🍜",
    gradient: "linear-gradient(135deg, #e8d5b7, #c9956c)",
    photo: "photo-1627308595186-e6bb36712645",
    youtubeId: "kAHGNV5NqfY",
    youtubeTitle: "Thai Basil Chilli Chicken — Marion's Kitchen",
    tags: ["global"],
    region: "Asia",
    minutes: 25,
    rating: 4.7,
    servings: 2,
    calories: 480,
    description: "Fiery, fragrant, and on the table in under 30 minutes — this Thai street-food classic is weeknight gold.",
    ingredients: [
      { qty: "300g", name: "Ground chicken" },
      { qty: "2 cloves", name: "Garlic" },
      { qty: "2", name: "Thai chilies" },
      { qty: "1 cup", name: "Holy basil" },
      { qty: "2 tbsp", name: "Fish sauce" },
    ],
    steps: [
      "Pound garlic and chilies into a rough paste.",
      "Stir-fry over high heat with chicken until browned.",
      "Add fish sauce and a splash of water.",
      "Toss in basil at the very end and serve over jasmine rice.",
    ],
  },
  {
    id: "sushi-rolls",
    name: "Homemade Sushi Rolls",
    emoji: "🍣",
    gradient: "linear-gradient(135deg, oklch(92% 0.02 80), oklch(40% 0.04 220))",
    photo: "photo-1579584425555-c3ce17fd4351",
    youtubeId: "nIoOv6lWYnk",
    youtubeTitle: "The Best Way To Make Sushi At Home | Epicurious 101",
    tags: ["global"],
    region: "Japan",
    minutes: 60,
    rating: 4.6,
    servings: 2,
    calories: 420,
    description: "Professional-quality sushi rolls at home. Once you master the rice, everything else falls into place.",
    ingredients: [
      { qty: "1½ cups", name: "Sushi rice" },
      { qty: "4 sheets", name: "Nori seaweed" },
      { qty: "150g", name: "Sashimi-grade salmon or tuna" },
      { qty: "1", name: "Avocado, sliced" },
      { qty: "1 tbsp", name: "Rice vinegar" },
      { qty: "to serve", name: "Soy sauce & wasabi" },
    ],
    steps: [
      "Cook sushi rice, season with rice vinegar, sugar, and salt while warm. Cool to room temperature.",
      "Lay nori on a bamboo mat, shiny side down. Spread rice evenly, leaving 2cm at the top.",
      "Arrange fish and avocado in a line across the centre.",
      "Roll tightly using the mat, sealing the edge with a little water. Slice with a wet knife.",
    ],
  },
  {
    id: "tagine",
    name: "Moroccan Chicken Tagine",
    emoji: "🥘",
    gradient: "linear-gradient(135deg, #d4e8c2, #7ab648)",
    photo: "photo-1541518763669-27fef04b14ea",
    imageUrl: "https://www.themealdb.com/images/media/meals/yuwtuu1511295751.jpg",
    youtubeId: "nZPaNd2S8Dw",
    youtubeTitle: "Moroccan Chicken Tagine | Food Wishes",
    tags: ["global"],
    region: "Africa",
    minutes: 55,
    rating: 4.8,
    servings: 4,
    calories: 520,
    description: "Bone-in chicken thighs slow-braised with preserved lemon, green olives, and warming Moroccan spices.",
    ingredients: [
      { qty: "8", name: "Chicken thighs, bone-in" },
      { qty: "1", name: "Preserved lemon, rinsed & sliced" },
      { qty: "1 cup", name: "Green olives, pitted" },
      { qty: "1½ tsp", name: "Ras el hanout" },
      { qty: "1 tsp", name: "Ground cumin" },
      { qty: "½ tsp", name: "Ground ginger" },
      { qty: "2", name: "Onions, thinly sliced" },
      { qty: "3 cloves", name: "Garlic, minced" },
      { qty: "handful", name: "Fresh coriander, chopped" },
    ],
    steps: [
      "Season chicken with ras el hanout, cumin, ginger, salt and pepper. Marinate 30 minutes if time allows.",
      "Brown chicken in olive oil, skin-side down, 5 minutes. Set aside.",
      "In the same pot, cook onions and garlic until softened. Add spices and stir 1 minute.",
      "Return chicken to pot, add 300ml water, preserved lemon and olives. Cover and simmer 40 minutes.",
      "Finish with fresh coriander and serve over couscous or with crusty bread.",
    ],
  },
  {
    id: "burrito-bowl",
    name: "Chicken Burrito Bowl",
    emoji: "🫔",
    gradient: "linear-gradient(135deg, oklch(92% 0.05 40), oklch(76% 0.14 75))",
    photo: "photo-1533606117812-0783e8e690f1",
    youtubeId: "7kCSWe8zwt0",
    youtubeTitle: "I Made Chipotle's Chicken Burrito Bowl At Home | Allrecipes",
    tags: ["global"],
    region: "Latam",
    minutes: 30,
    rating: 4.6,
    servings: 2,
    calories: 620,
    description: "Everything you love about Chipotle, made at home — juicy chicken, cilantro rice, beans, and avocado.",
    ingredients: [
      { qty: "300g", name: "Chicken thighs" },
      { qty: "1 cup", name: "Cilantro lime rice" },
      { qty: "1 cup", name: "Black beans" },
      { qty: "½ cup", name: "Corn salsa" },
      { qty: "1", name: "Avocado" },
    ],
    steps: [
      "Marinate chicken in lime, garlic, and cumin.",
      "Sear until golden and cooked through; rest, then slice.",
      "Build bowls with rice, beans, corn, and chicken.",
      "Top with avocado and a squeeze of lime.",
    ],
  },
  {
    id: "pad-thai",
    name: "Pad Thai",
    emoji: "🍜",
    gradient: "linear-gradient(135deg, oklch(88% 0.10 60), oklch(70% 0.15 45))",
    photo: "photo-1637806930600-37fa8892069d",
    youtubeId: "70vfRls1vqA",
    youtubeTitle: "Pad Thai — Marion's Kitchen",
    tags: ["global", "quick"],
    region: "Thailand",
    minutes: 25,
    rating: 4.8,
    servings: 2,
    calories: 520,
    description: "Thailand's most beloved noodle dish — sweet, sour, savoury, and satisfying in every mouthful.",
    ingredients: [
      { qty: "200g", name: "Flat rice noodles" },
      { qty: "200g", name: "Prawns or chicken, sliced" },
      { qty: "2", name: "Eggs" },
      { qty: "1 cup", name: "Bean sprouts" },
      { qty: "3 tbsp", name: "Fish sauce" },
      { qty: "2 tbsp", name: "Tamarind paste" },
      { qty: "1 tbsp", name: "Palm sugar or brown sugar" },
      { qty: "¼ cup", name: "Roasted peanuts, crushed" },
      { qty: "1", name: "Lime, wedged" },
    ],
    steps: [
      "Soak rice noodles in warm water 30 minutes until pliable; drain.",
      "Mix fish sauce, tamarind, and sugar into a sauce.",
      "Stir-fry protein in a hot wok until cooked. Push to the side and scramble eggs.",
      "Add noodles and sauce, toss everything together over high heat.",
      "Fold in bean sprouts. Serve topped with peanuts and lime wedges.",
    ],
  },
  {
    id: "bibimbap",
    name: "Korean Bibimbap",
    emoji: "🍚",
    gradient: "linear-gradient(135deg, oklch(80% 0.12 35), oklch(60% 0.08 130))",
    photo: "photo-1590301157890-4810ed352733",
    youtubeId: "6QQ67F8y2b8",
    youtubeTitle: "Bibimbap Recipe — Maangchi",
    tags: ["global"],
    region: "Korea",
    minutes: 40,
    rating: 4.7,
    servings: 2,
    calories: 580,
    description: "The Korean bowl of everything — fluffy rice, seasoned vegetables, savoury beef, and a spicy gochujang drizzle.",
    ingredients: [
      { qty: "2 cups", name: "Short-grain rice, cooked" },
      { qty: "200g", name: "Beef mince" },
      { qty: "1", name: "Carrot, julienned" },
      { qty: "2 cups", name: "Spinach, blanched" },
      { qty: "1 cup", name: "Bean sprouts, blanched" },
      { qty: "150g", name: "Mushrooms, sautéed" },
      { qty: "2", name: "Eggs" },
      { qty: "2 tbsp", name: "Gochujang (Korean chilli paste)" },
      { qty: "1 tbsp", name: "Sesame oil" },
    ],
    steps: [
      "Cook each vegetable separately in sesame oil with a pinch of salt and a dash of soy sauce. Set aside.",
      "Brown beef mince with garlic, soy sauce, and a little sugar. Set aside.",
      "Fry eggs sunny-side up.",
      "Arrange rice in bowls. Place each vegetable and beef in separate sections around the bowl.",
      "Top with a fried egg and a dollop of gochujang. Drizzle sesame oil, mix everything together before eating.",
    ],
  },
  {
    id: "tikka-masala",
    name: "Chicken Tikka Masala",
    emoji: "🍛",
    gradient: "linear-gradient(135deg, oklch(78% 0.14 40), oklch(55% 0.15 35))",
    photo: "photo-1565557623262-b51c2513a641",
    youtubeId: "ysUumkRFP8I",
    youtubeTitle: "Chicken Tikka Masala — RecipeTin Eats",
    tags: ["global"],
    region: "India",
    minutes: 50,
    rating: 4.9,
    servings: 4,
    calories: 560,
    description: "Charred chicken tikka simmered in a velvety, spiced tomato-cream sauce. The dish the world fell in love with.",
    ingredients: [
      { qty: "600g", name: "Chicken breast, cubed" },
      { qty: "150ml", name: "Plain yogurt" },
      { qty: "2 tsp", name: "Garam masala" },
      { qty: "1 tsp each", name: "Turmeric, cumin, paprika" },
      { qty: "1", name: "Onion, diced" },
      { qty: "4 cloves", name: "Garlic, minced" },
      { qty: "1 tbsp", name: "Fresh ginger, grated" },
      { qty: "400g", name: "Crushed tomatoes" },
      { qty: "100ml", name: "Double cream" },
    ],
    steps: [
      "Marinate chicken in yogurt, half the spices, salt, and garlic for at least 30 minutes.",
      "Grill or broil marinated chicken on high heat until slightly charred — 8–10 minutes.",
      "Sauté onion in butter until golden. Add garlic, ginger, and remaining spices; cook 2 minutes.",
      "Add crushed tomatoes and simmer 15 minutes. Blend the sauce until smooth.",
      "Stir in cream and the grilled chicken. Simmer 10 minutes and serve with basmati rice.",
    ],
  },
  {
    id: "falafel",
    name: "Crispy Falafel",
    emoji: "🧆",
    gradient: "linear-gradient(135deg, oklch(82% 0.09 100), oklch(65% 0.12 90))",
    photo: "photo-1593001872095-7d5b3868fb1d",
    youtubeId: "NZcWedPKysk",
    youtubeTitle: "The Best Falafel Recipe — Serious Eats",
    tags: ["global", "veg", "snack"],
    region: "Middle East",
    minutes: 35,
    rating: 4.7,
    servings: 4,
    calories: 340,
    description: "Golden, crunchy outside and herb-green inside — proper falafel made with raw (not canned) chickpeas.",
    ingredients: [
      { qty: "400g", name: "Dried chickpeas, soaked overnight" },
      { qty: "1", name: "Onion, roughly chopped" },
      { qty: "4 cloves", name: "Garlic" },
      { qty: "1 cup", name: "Fresh parsley" },
      { qty: "½ cup", name: "Fresh coriander" },
      { qty: "1 tsp each", name: "Cumin, coriander powder" },
      { qty: "1 tsp", name: "Baking powder" },
      { qty: "oil", name: "For frying" },
    ],
    steps: [
      "Drain soaked chickpeas (do NOT cook them — they must stay raw for texture).",
      "Blend chickpeas, onion, garlic, herbs and spices until a coarse paste forms. Season well.",
      "Stir in baking powder. Refrigerate 30 minutes. Form into balls the size of golf balls.",
      "Deep-fry in oil at 175°C for 3–4 minutes until dark golden. Drain on paper towels.",
      "Serve in flatbread with tahini, tomatoes, and pickled vegetables.",
    ],
  },
  {
    id: "gyoza",
    name: "Pan-fried Gyoza",
    emoji: "🥟",
    gradient: "linear-gradient(135deg, oklch(95% 0.03 80), oklch(78% 0.08 55))",
    photo: "photo-1589047133481-02b4a5327d89",
    youtubeId: "XYLyVZW2dcQ",
    youtubeTitle: "How To Make Gyoza — Joshua Weissman",
    tags: ["global", "snack"],
    region: "Japan",
    minutes: 35,
    rating: 4.7,
    servings: 4,
    calories: 280,
    description: "Crispy on the bottom, steamed-tender on top — the Japanese dumpling technique that makes every gyoza perfect.",
    ingredients: [
      { qty: "24", name: "Gyoza wrappers" },
      { qty: "300g", name: "Pork mince" },
      { qty: "1 cup", name: "Napa cabbage, finely shredded" },
      { qty: "2 cloves", name: "Garlic, minced" },
      { qty: "1 tsp", name: "Fresh ginger, grated" },
      { qty: "2 tbsp", name: "Soy sauce" },
      { qty: "1 tbsp", name: "Sesame oil" },
    ],
    steps: [
      "Salt cabbage and let stand 10 minutes; squeeze out excess moisture.",
      "Mix pork, cabbage, garlic, ginger, soy sauce, and sesame oil.",
      "Place a teaspoon of filling in each wrapper. Dampen edge, fold, and pleat to seal.",
      "Fry gyoza flat-side down in a little oil for 2–3 minutes until golden.",
      "Add ¼ cup water, cover immediately and steam 3 minutes. Remove lid and fry off any remaining water.",
      "Serve with soy sauce mixed with rice vinegar and chilli oil.",
    ],
  },

  /* ─────────────────────── SALADS ─────────────────────────── */
  {
    id: "greek-salad",
    name: "Greek Salad",
    emoji: "🥗",
    gradient: "linear-gradient(135deg, oklch(90% 0.06 200), oklch(72% 0.10 145))",
    photo: "photo-1607532941433-304659e8198a",
    youtubeId: "J3hrMqM3N00",
    youtubeTitle: "Authentic Greek Salad (Horiatiki) — Akis Kitchen",
    tags: ["global", "salad", "veg", "quick"],
    region: "Greece",
    minutes: 15,
    rating: 4.7,
    servings: 2,
    calories: 280,
    description: "The Aegean sun in a bowl — chunky tomatoes, crisp cucumber, tangy olives and a slab of creamy feta.",
    ingredients: [
      { qty: "400g", name: "Ripe tomatoes, chunked" },
      { qty: "1", name: "Cucumber, chunked" },
      { qty: "½", name: "Red onion, thinly sliced" },
      { qty: "½ cup", name: "Kalamata olives" },
      { qty: "150g", name: "Feta cheese, whole slab" },
      { qty: "3 tbsp", name: "Extra virgin olive oil" },
      { qty: "1 tsp", name: "Dried oregano" },
    ],
    steps: [
      "Combine tomatoes, cucumber, red onion, and olives in a wide bowl.",
      "Place feta slab whole on top — do not crumble it.",
      "Drizzle generously with olive oil, scatter oregano over everything.",
      "Season with a little salt and black pepper. Serve with crusty bread to mop up the juices.",
    ],
  },
  {
    id: "caesar-salad",
    name: "Caesar Salad",
    emoji: "🥗",
    gradient: "linear-gradient(135deg, oklch(95% 0.03 95), oklch(80% 0.08 95))",
    photo: "photo-1546793665-c74683f339c1",
    youtubeId: "_YCJ2Sfdl3U",
    youtubeTitle: "The Ultimate Caesar Salad — Bon Appétit",
    tags: ["quick", "salad"],
    minutes: 15,
    rating: 4.6,
    servings: 2,
    calories: 320,
    description: "The gold standard of salads — crisp romaine, umami-packed dressing, shaved parmesan, and hand-torn croutons.",
    ingredients: [
      { qty: "2 heads", name: "Romaine lettuce, torn" },
      { qty: "50g", name: "Parmesan, shaved" },
      { qty: "1 cup", name: "Croutons" },
      { qty: "4 tbsp", name: "Caesar dressing" },
      { qty: "1 tsp", name: "Anchovy paste (optional)" },
      { qty: "½", name: "Lemon, juiced" },
    ],
    steps: [
      "Tear romaine into large pieces — keep them chunky for texture.",
      "Whisk Caesar dressing with anchovy paste and a squeeze of lemon.",
      "Toss lettuce with dressing, ensuring every leaf is coated.",
      "Top with parmesan shavings and croutons. Serve immediately.",
    ],
  },
  {
    id: "watermelon-salad",
    name: "Watermelon Feta Salad",
    emoji: "🍉",
    gradient: "linear-gradient(135deg, oklch(82% 0.14 15), oklch(88% 0.08 145))",
    photo: "photo-1626303551646-69dbd1ab24be",
    youtubeId: "GFytqjoS6cg",
    youtubeTitle: "Watermelon Feta Salad — Tasty",
    tags: ["quick", "salad", "veg"],
    minutes: 10,
    rating: 4.5,
    servings: 4,
    calories: 180,
    description: "Summer's greatest combination — sweet cold watermelon, salty feta, fresh mint and a lime kick.",
    ingredients: [
      { qty: "½", name: "Small watermelon, cubed" },
      { qty: "100g", name: "Feta cheese, crumbled" },
      { qty: "handful", name: "Fresh mint leaves" },
      { qty: "¼", name: "Red onion, thinly sliced" },
      { qty: "2 tbsp", name: "Lime juice" },
      { qty: "1 tbsp", name: "Extra virgin olive oil" },
    ],
    steps: [
      "Cut watermelon into 3cm cubes, removing seeds.",
      "Arrange on a platter with red onion slices.",
      "Scatter crumbled feta and torn mint leaves over the top.",
      "Drizzle with lime juice and olive oil. Serve cold immediately.",
    ],
  },
  {
    id: "caprese",
    name: "Caprese Salad",
    emoji: "🍅",
    gradient: "linear-gradient(135deg, oklch(78% 0.14 25), oklch(95% 0.02 80))",
    photo: "photo-1595587870672-c79b47875c6a",
    youtubeId: "pgLhokt0uAQ",
    youtubeTitle: "Classic Caprese Salad — Gennaro Contaldo",
    tags: ["global", "salad", "veg", "quick"],
    region: "Italy",
    minutes: 10,
    rating: 4.7,
    servings: 2,
    calories: 260,
    description: "Simple as the Italian flag it mirrors — ripe tomatoes, fresh mozzarella, basil, and the best olive oil you own.",
    ingredients: [
      { qty: "3 large", name: "Ripe tomatoes" },
      { qty: "250g", name: "Fresh buffalo mozzarella" },
      { qty: "handful", name: "Fresh basil" },
      { qty: "3 tbsp", name: "Extra virgin olive oil" },
      { qty: "1 tbsp", name: "Balsamic glaze" },
      { qty: "to taste", name: "Flaky sea salt & black pepper" },
    ],
    steps: [
      "Slice tomatoes and mozzarella to equal thickness — about 1cm.",
      "Alternate slices on a plate, slightly overlapping.",
      "Tuck whole basil leaves between the slices.",
      "Drizzle with olive oil and balsamic glaze. Finish with flaky salt and black pepper.",
    ],
  },

  /* ─────────────────────── SOUPS ──────────────────────────── */
  {
    id: "french-onion-soup",
    name: "French Onion Soup",
    emoji: "🧅",
    gradient: "linear-gradient(135deg, oklch(72% 0.10 55), oklch(45% 0.08 50))",
    photo: "photo-1549203438-a7696aed4dac",
    youtubeId: "cYY6mBu-UQ0",
    youtubeTitle: "French Onion Soup — Jacques Pépin",
    tags: ["global", "soup"],
    region: "France",
    minutes: 70,
    rating: 4.8,
    servings: 4,
    calories: 380,
    description: "Forty minutes of caramelised onions pay off in a soup so deep and rich you'll taste the bistro in Paris.",
    ingredients: [
      { qty: "6 large", name: "Onions, thinly sliced" },
      { qty: "3 tbsp", name: "Butter" },
      { qty: "100ml", name: "Dry white wine" },
      { qty: "1.5L", name: "Beef stock" },
      { qty: "2 sprigs", name: "Fresh thyme" },
      { qty: "4 slices", name: "Baguette, toasted" },
      { qty: "150g", name: "Gruyère cheese, grated" },
    ],
    steps: [
      "Melt butter in a large heavy pot. Add onions and cook on medium-low, stirring regularly, for 40–45 minutes until deeply caramelised and golden.",
      "Deglaze with white wine, scraping up any bits from the bottom. Cook 2 minutes.",
      "Add stock and thyme. Simmer 15 minutes. Season generously.",
      "Ladle into oven-safe bowls. Place a toasted baguette slice on top of each.",
      "Pile Gruyère generously over the bread and broil 3–4 minutes until bubbling and golden. Serve immediately.",
    ],
  },
  {
    id: "tom-yum",
    name: "Tom Yum Soup",
    emoji: "🍲",
    gradient: "linear-gradient(135deg, oklch(78% 0.14 25), oklch(58% 0.12 45))",
    photo: "photo-1628430043175-0e8820df47c3",
    youtubeId: "hXaaZiMgvgI",
    youtubeTitle: "Authentic Tom Yum Soup — Pailin's Kitchen",
    tags: ["global", "soup"],
    region: "Thailand",
    minutes: 30,
    rating: 4.7,
    servings: 2,
    calories: 220,
    description: "The electric trio of lemongrass, galangal and kaffir lime gives this Thai soup its unforgettable punch.",
    ingredients: [
      { qty: "300g", name: "Prawns, peeled & deveined" },
      { qty: "2 stalks", name: "Lemongrass, bruised" },
      { qty: "6", name: "Kaffir lime leaves" },
      { qty: "4 slices", name: "Galangal (or ginger)" },
      { qty: "1 cup", name: "Mushrooms, halved" },
      { qty: "3 tbsp", name: "Fish sauce" },
      { qty: "3 tbsp", name: "Lime juice" },
      { qty: "2", name: "Red bird's eye chillies, crushed" },
      { qty: "1 tsp", name: "Sugar" },
    ],
    steps: [
      "Bring 700ml water to a boil. Add lemongrass, galangal, and kaffir lime leaves. Simmer 5 minutes.",
      "Add mushrooms and cook 3 minutes.",
      "Add prawns and cook just until pink — about 2 minutes.",
      "Season with fish sauce, lime juice, sugar, and chillies. Taste and adjust the balance.",
      "Ladle into bowls and garnish with coriander leaves. Remove lemongrass and galangal before eating.",
    ],
  },

  /* ─────────────────────── DESSERTS ───────────────────────── */
  {
    id: "tiramisu",
    name: "Tiramisu",
    emoji: "🍮",
    gradient: "linear-gradient(135deg, oklch(88% 0.05 75), oklch(55% 0.08 50))",
    photo: "photo-1571877227200-a0d98ea607e9",
    youtubeId: "ayiiE6RPDFw",
    youtubeTitle: "Classic Tiramisu — Italia Squisita",
    tags: ["global", "dessert"],
    region: "Italy",
    minutes: 30,
    rating: 4.9,
    servings: 6,
    calories: 450,
    description: "Italy's greatest gift to dessert — espresso-soaked ladyfingers, silky mascarpone cream, and a cloud of cocoa.",
    ingredients: [
      { qty: "500g", name: "Mascarpone cheese" },
      { qty: "4", name: "Eggs, separated" },
      { qty: "100g", name: "Caster sugar" },
      { qty: "300ml", name: "Strong espresso, cooled" },
      { qty: "300g", name: "Savoiardi ladyfingers" },
      { qty: "3 tbsp", name: "Marsala wine or dark rum" },
      { qty: "3 tbsp", name: "Cocoa powder, for dusting" },
    ],
    steps: [
      "Whisk egg yolks and sugar until pale and doubled in volume, about 5 minutes.",
      "Beat in mascarpone until smooth. In a separate bowl, whisk egg whites to stiff peaks.",
      "Gently fold egg whites into the mascarpone mixture in two additions.",
      "Mix espresso with marsala. Quickly dip each ladyfinger and arrange in a single layer in a dish.",
      "Spread half the cream over the ladyfingers. Add another dipped layer, then remaining cream.",
      "Refrigerate at least 4 hours or overnight. Dust generously with cocoa before serving.",
    ],
  },
  {
    id: "creme-brulee",
    name: "Crème Brûlée",
    emoji: "🍮",
    gradient: "linear-gradient(135deg, oklch(95% 0.06 80), oklch(80% 0.12 65))",
    photo: "photo-1554371650-1f19f803c220",
    youtubeId: "jcoGuoHmiEg",
    youtubeTitle: "Crème Brûlée — Jacques Pépin",
    tags: ["global", "dessert"],
    region: "France",
    minutes: 50,
    rating: 4.8,
    servings: 4,
    calories: 380,
    description: "The satisfying crack of caramel glass over silky vanilla custard — the ultimate show-off dessert.",
    ingredients: [
      { qty: "500ml", name: "Double cream" },
      { qty: "5", name: "Egg yolks" },
      { qty: "80g", name: "Caster sugar" },
      { qty: "1", name: "Vanilla bean, split" },
      { qty: "4 tbsp", name: "Caster sugar, for brûlée top" },
    ],
    steps: [
      "Heat cream with vanilla bean and seeds until just below simmering. Remove bean.",
      "Whisk egg yolks with sugar until pale. Slowly pour warm cream into yolks, whisking constantly.",
      "Strain into ramekins. Place in a baking dish and fill with boiling water halfway up the sides.",
      "Bake at 160°C for 35–40 minutes until set with a slight wobble in the centre. Chill 2 hours.",
      "Sprinkle 1 tbsp sugar over each ramekin. Blowtorch in circular motions until caramel forms. Serve immediately.",
    ],
  },
  {
    id: "mango-sticky-rice",
    name: "Mango Sticky Rice",
    emoji: "🥭",
    gradient: "linear-gradient(135deg, oklch(90% 0.12 75), oklch(75% 0.16 65))",
    photo: "photo-1582801205465-c0d029e85a1c",
    youtubeId: "HoB9Uj1cdts",
    youtubeTitle: "Mango Sticky Rice — Hot Thai Kitchen",
    tags: ["global", "dessert", "veg"],
    region: "Thailand",
    minutes: 35,
    rating: 4.8,
    servings: 2,
    calories: 420,
    description: "Fragrant coconut-soaked glutinous rice alongside ripe juicy mango — Thailand's most beloved dessert.",
    ingredients: [
      { qty: "1 cup", name: "Glutinous rice, soaked 4h" },
      { qty: "400ml", name: "Coconut milk" },
      { qty: "4 tbsp", name: "Sugar" },
      { qty: "½ tsp", name: "Salt" },
      { qty: "2 ripe", name: "Mangoes" },
      { qty: "1 tsp", name: "Toasted sesame seeds (optional)" },
    ],
    steps: [
      "Steam soaked glutinous rice 20–25 minutes until tender.",
      "Heat coconut milk with sugar and salt until dissolved — do not boil.",
      "Pour ¾ of the coconut sauce over hot rice. Stir and let absorb 15 minutes.",
      "Peel and slice mangoes. Serve rice alongside mango, drizzled with remaining coconut sauce.",
    ],
  },
  {
    id: "lava-cake",
    name: "Chocolate Lava Cake",
    emoji: "🍫",
    gradient: "linear-gradient(135deg, oklch(30% 0.05 30), oklch(50% 0.08 40))",
    photo: "photo-1605807646983-377bc5a76493",
    youtubeId: "gW3JtHpuzrk",
    youtubeTitle: "Molten Chocolate Lava Cakes — Preppy Kitchen",
    tags: ["dessert", "quick"],
    minutes: 22,
    rating: 4.9,
    servings: 4,
    calories: 350,
    description: "Four ingredients, twenty minutes, and a moment of pure drama — the molten lava cake never gets old.",
    ingredients: [
      { qty: "200g", name: "Dark chocolate (70%), chopped" },
      { qty: "100g", name: "Butter, plus extra for moulds" },
      { qty: "4", name: "Eggs" },
      { qty: "100g", name: "Caster sugar" },
      { qty: "3 tbsp", name: "Plain flour" },
      { qty: "pinch", name: "Salt" },
    ],
    steps: [
      "Butter and dust 4 ramekins with cocoa. Preheat oven to 200°C.",
      "Melt chocolate and butter together in a bowl over simmering water. Stir until smooth.",
      "Whisk eggs and sugar until pale. Fold in melted chocolate, then flour and salt.",
      "Divide batter between ramekins. Bake 10–12 minutes — the edges must be set, centre still soft.",
      "Run a knife around the edge, invert onto plates. Serve immediately with ice cream.",
    ],
  },
  {
    id: "baklava",
    name: "Baklava",
    emoji: "🍯",
    gradient: "linear-gradient(135deg, oklch(88% 0.12 75), oklch(65% 0.12 55))",
    photo: "photo-1598110750624-207050c4f28c",
    youtubeId: "EBHlZQn14C0",
    youtubeTitle: "How to Make Baklava — Joshua Weissman",
    tags: ["global", "dessert"],
    region: "Middle East",
    minutes: 90,
    rating: 4.8,
    servings: 12,
    calories: 280,
    description: "Paper-thin phyllo, fragrant walnuts, and rose-water honey syrup — the jewel of Middle Eastern baking.",
    ingredients: [
      { qty: "1 pack (400g)", name: "Phyllo pastry, thawed" },
      { qty: "200g", name: "Unsalted butter, melted" },
      { qty: "2 cups", name: "Walnuts, finely chopped" },
      { qty: "1 tsp", name: "Cinnamon" },
      { qty: "1 cup", name: "Honey" },
      { qty: "½ cup", name: "Water" },
      { qty: "½ cup", name: "Sugar" },
      { qty: "1 tbsp", name: "Rose water or orange blossom water" },
    ],
    steps: [
      "Mix walnuts with cinnamon. Preheat oven to 170°C.",
      "Butter a baking tin. Layer 8 sheets of phyllo, brushing each with melted butter.",
      "Spread a third of the walnut mixture. Repeat layers twice more. Finish with 8 buttered phyllo sheets.",
      "Cut into diamond shapes with a sharp knife. Bake 40–45 minutes until deep golden.",
      "Meanwhile, simmer honey, water, and sugar 10 minutes until slightly thickened. Add rose water.",
      "Pour warm syrup over hot baklava the moment it comes from the oven. Cool 2 hours before serving.",
    ],
  },
  {
    id: "churros",
    name: "Churros",
    emoji: "🍩",
    gradient: "linear-gradient(135deg, oklch(90% 0.10 75), oklch(68% 0.12 55))",
    photo: "photo-1624371414361-e670edf4898d",
    youtubeId: "Yy2MZuUY5XI",
    youtubeTitle: "Churros with Chocolate Sauce — Tasty",
    tags: ["global", "dessert", "snack"],
    region: "Spain",
    minutes: 30,
    rating: 4.6,
    servings: 4,
    calories: 320,
    description: "Crispy, ridged dough sticks rolled in cinnamon sugar — best eaten hot, dunked in thick chocolate sauce.",
    ingredients: [
      { qty: "1 cup", name: "Plain flour" },
      { qty: "1 cup", name: "Water" },
      { qty: "2 tbsp", name: "Butter" },
      { qty: "½ tsp", name: "Salt" },
      { qty: "oil", name: "For deep-frying" },
      { qty: "½ cup", name: "Caster sugar" },
      { qty: "1 tsp", name: "Ground cinnamon" },
      { qty: "100g", name: "Dark chocolate (for dipping sauce)" },
    ],
    steps: [
      "Bring water, butter, and salt to a boil. Add flour and stir vigorously until dough pulls away from sides.",
      "Cool slightly, then pipe long strips into hot oil (175°C) using a star-tipped piping bag.",
      "Fry 2–3 minutes per side until golden. Drain on paper towels.",
      "Toss warm churros in cinnamon sugar. Melt chocolate with a splash of cream for dipping sauce.",
    ],
  },
  {
    id: "fruit-tart",
    name: "Fresh Fruit Tart",
    emoji: "🍑",
    gradient: "linear-gradient(135deg, oklch(92% 0.06 80), oklch(80% 0.10 20))",
    photo: "photo-1495147466023-ac5c588e2e94",
    youtubeId: "6c2Sm8MeCfw",
    youtubeTitle: "French Fruit Tart — Sugar Spun Run",
    tags: ["dessert", "global"],
    region: "France",
    minutes: 75,
    rating: 4.7,
    servings: 8,
    calories: 320,
    description: "A buttery pastry shell filled with silky vanilla cream, crowned with glistening seasonal fruit.",
    ingredients: [
      { qty: "1", name: "Sweet pastry shell, baked blind" },
      { qty: "4", name: "Egg yolks" },
      { qty: "80g", name: "Caster sugar" },
      { qty: "3 tbsp", name: "Cornflour" },
      { qty: "500ml", name: "Whole milk" },
      { qty: "1 tsp", name: "Vanilla extract" },
      { qty: "30g", name: "Butter" },
      { qty: "assorted", name: "Fresh berries, kiwi, mandarin segments" },
      { qty: "2 tbsp", name: "Apricot jam (for glaze)" },
    ],
    steps: [
      "Whisk egg yolks, sugar, and cornflour together in a bowl.",
      "Heat milk until steaming. Pour slowly into egg mixture, whisking constantly.",
      "Return to pan and cook on medium, stirring, until thick. Remove from heat and stir in butter and vanilla.",
      "Press cling film onto the surface of the cream and refrigerate until cold.",
      "Spread pastry cream in the tart shell. Arrange fruit decoratively on top.",
      "Warm apricot jam with a splash of water and brush over fruit for a glossy finish.",
    ],
  },

  /* ─────────────────────── SNACKS ─────────────────────────── */
  {
    id: "guacamole",
    name: "Guacamole",
    emoji: "🥑",
    gradient: "linear-gradient(135deg, oklch(80% 0.12 145), oklch(60% 0.10 130))",
    photo: "photo-1595016111459-799a195e7452",
    youtubeId: "a6yCQdx3Pkg",
    youtubeTitle: "The Best Guacamole — Rick Bayless",
    tags: ["quick", "snack", "veg", "global"],
    region: "Mexico",
    minutes: 10,
    rating: 4.8,
    servings: 4,
    calories: 180,
    description: "The only guacamole recipe you need — ripe avocados, a little heat, and nothing unnecessary.",
    ingredients: [
      { qty: "3 ripe", name: "Avocados" },
      { qty: "2 tbsp", name: "Lime juice (about 1 lime)" },
      { qty: "¼", name: "Red onion, finely diced" },
      { qty: "1", name: "Jalapeño, seeds removed, finely diced" },
      { qty: "2 tbsp", name: "Fresh coriander, chopped" },
      { qty: "1 medium", name: "Tomato, diced" },
      { qty: "to taste", name: "Salt" },
    ],
    steps: [
      "Halve and pit avocados. Scoop flesh into a bowl.",
      "Add lime juice and salt, then mash with a fork — leave some chunks for texture.",
      "Fold in onion, jalapeño, coriander, and tomato.",
      "Taste and adjust seasoning. Serve immediately with tortilla chips.",
    ],
  },
  {
    id: "hummus",
    name: "Silky Hummus",
    emoji: "🫙",
    gradient: "linear-gradient(135deg, oklch(92% 0.07 75), oklch(80% 0.10 65))",
    photo: "photo-1603133872497-f29809b750bf",
    youtubeId: "tsx1t6lMt8k",
    youtubeTitle: "The Creamiest Hummus — Sohla El-Waylly",
    tags: ["global", "snack", "veg"],
    region: "Middle East",
    minutes: 15,
    rating: 4.7,
    servings: 6,
    calories: 160,
    description: "Silkier than you thought possible — the secret is ice-cold water blended in for a full two minutes.",
    ingredients: [
      { qty: "400g tin", name: "Chickpeas, drained (liquid reserved)" },
      { qty: "3 tbsp", name: "Good-quality tahini" },
      { qty: "3 tbsp", name: "Lemon juice" },
      { qty: "2 cloves", name: "Garlic" },
      { qty: "3 tbsp", name: "Ice-cold water" },
      { qty: "½ tsp", name: "Cumin" },
      { qty: "3 tbsp", name: "Extra virgin olive oil" },
      { qty: "pinch", name: "Paprika, to finish" },
    ],
    steps: [
      "Reserve a few chickpeas for garnish. Blend the rest with tahini, lemon juice, and garlic until very smooth.",
      "With the blender running, stream in ice-cold water. Keep blending 2 full minutes — this is what makes it silky.",
      "Season with cumin and salt. Taste and adjust lemon.",
      "Spread into a bowl, swirl with the back of a spoon. Drizzle with olive oil, add reserved chickpeas and paprika.",
    ],
  },
  {
    id: "bruschetta",
    name: "Bruschetta al Pomodoro",
    emoji: "🍞",
    gradient: "linear-gradient(135deg, oklch(82% 0.13 25), oklch(88% 0.08 75))",
    photo: "photo-1572695157366-5e585ab2b69f",
    youtubeId: "Q3xg35pcLyo",
    youtubeTitle: "Classic Bruschetta — Gennaro Contaldo",
    tags: ["quick", "snack", "veg"],
    region: "Italy",
    minutes: 15,
    rating: 4.6,
    servings: 4,
    calories: 220,
    description: "Charred bread, the best tomatoes, torn basil, and proper olive oil — Italian simplicity at its finest.",
    ingredients: [
      { qty: "1 loaf", name: "Ciabatta or sourdough, sliced" },
      { qty: "300g", name: "Ripe cherry tomatoes, quartered" },
      { qty: "2 cloves", name: "Garlic (1 for rubbing, 1 minced)" },
      { qty: "handful", name: "Fresh basil, torn" },
      { qty: "3 tbsp", name: "Extra virgin olive oil" },
      { qty: "to taste", name: "Salt & black pepper" },
    ],
    steps: [
      "Grill or toast bread slices until charred and crisp on both sides.",
      "Immediately rub each slice with the cut side of a garlic clove.",
      "Mix tomatoes with minced garlic, basil, olive oil, salt, and pepper. Rest 5 minutes.",
      "Spoon tomato mixture generously over bread and serve straight away.",
    ],
  },
  {
    id: "banana-bread",
    name: "Banana Bread",
    emoji: "🍌",
    gradient: "linear-gradient(135deg, oklch(88% 0.10 80), oklch(68% 0.10 60))",
    photo: "photo-1569762404472-026308ba6b64",
    youtubeId: "Ob8eL4mMOys",
    youtubeTitle: "The Best Banana Bread — Binging with Babish",
    tags: ["snack", "breakfast"],
    minutes: 70,
    rating: 4.8,
    servings: 8,
    calories: 290,
    description: "The recipe everyone should know — deeply banana-flavoured, moist, and better on day two.",
    ingredients: [
      { qty: "3", name: "Very ripe bananas, mashed" },
      { qty: "190g", name: "Plain flour" },
      { qty: "100g", name: "Caster sugar" },
      { qty: "75g", name: "Butter, melted" },
      { qty: "2", name: "Eggs" },
      { qty: "1 tsp", name: "Vanilla extract" },
      { qty: "1 tsp", name: "Baking soda" },
      { qty: "¼ tsp", name: "Salt" },
      { qty: "½ cup", name: "Walnuts, chopped (optional)" },
    ],
    steps: [
      "Preheat oven to 175°C. Grease and line a loaf tin.",
      "Whisk melted butter and sugar. Add eggs, vanilla, and mashed bananas.",
      "Fold in flour, baking soda, and salt until just combined — do not overmix.",
      "Stir in walnuts if using. Pour into tin.",
      "Bake 55–65 minutes until a skewer comes out clean. Cool in tin 10 minutes, then on a rack.",
    ],
  },

  /* ─────────────────────── BREAKFAST ──────────────────────── */
  {
    id: "acai-bowl",
    name: "Açaí Bowl",
    emoji: "🫐",
    gradient: "linear-gradient(135deg, oklch(45% 0.12 295), oklch(60% 0.14 300))",
    photo: "photo-1654923064926-be7e64267a31",
    youtubeId: "LmBZ5VasP_k",
    youtubeTitle: "Açaí Bowl — Downshiftology",
    tags: ["breakfast", "veg"],
    region: "Brazil",
    minutes: 10,
    rating: 4.6,
    servings: 1,
    calories: 380,
    description: "Brazil's superfood bowl — thick blended açaí with layered granola, fresh fruit, and a drizzle of honey.",
    ingredients: [
      { qty: "200g", name: "Frozen açaí purée packets" },
      { qty: "1", name: "Frozen banana" },
      { qty: "½ cup", name: "Frozen mixed berries" },
      { qty: "3 tbsp", name: "Almond milk (or coconut water)" },
      { qty: "¼ cup", name: "Granola" },
      { qty: "assorted", name: "Fresh fruit (banana, berries, mango)" },
      { qty: "1 tbsp", name: "Honey or agave" },
    ],
    steps: [
      "Break frozen açaí into chunks. Blend with frozen banana, berries, and almond milk.",
      "Blend on low first, then increase — add more liquid only if needed. Mixture must be thick, not pourable.",
      "Pour into a bowl — it should hold its shape.",
      "Top immediately with granola, fresh fruit, and a drizzle of honey.",
    ],
  },
  {
    id: "pancakes",
    name: "Classic Pancakes",
    emoji: "🥞",
    gradient: "linear-gradient(135deg, oklch(92% 0.08 80), oklch(82% 0.12 65))",
    photo: "photo-1528207776546-365bb710ee93",
    youtubeId: "vkcHmpKxFwg",
    youtubeTitle: "Perfect Fluffy Pancakes — Joshua Weissman",
    tags: ["breakfast", "quick"],
    minutes: 20,
    rating: 4.7,
    servings: 2,
    calories: 420,
    description: "Fluffy, golden-edged pancakes with pillowy middles — the weekend breakfast that never disappoints.",
    ingredients: [
      { qty: "1 cup", name: "Plain flour" },
      { qty: "1 cup", name: "Whole milk" },
      { qty: "1", name: "Egg" },
      { qty: "2 tbsp", name: "Butter, melted, plus extra for cooking" },
      { qty: "2 tbsp", name: "Caster sugar" },
      { qty: "1½ tsp", name: "Baking powder" },
      { qty: "¼ tsp", name: "Salt" },
      { qty: "to serve", name: "Maple syrup & fresh berries" },
    ],
    steps: [
      "Whisk flour, sugar, baking powder, and salt in a bowl.",
      "In another bowl, whisk milk, egg, and melted butter.",
      "Pour wet ingredients into dry. Stir until just combined — lumps are fine, do not overmix.",
      "Heat a pan on medium-low, brush with butter. Pour in ¼ cup batter per pancake.",
      "Cook until bubbles form and edges look set — about 2 minutes. Flip once and cook 1–2 minutes more.",
      "Serve with maple syrup and berries.",
    ],
  },
];

// ── Merge in TheMealDB imports ──────────────────────────────────────────
// The hand-curated `recipes` above stays as the featured/seed catalog.
// `importedRecipes` adds ~420 real dishes from TheMealDB with real images.
import { importedRecipes } from "./recipes.generated";
recipes.push(...importedRecipes);

export const featured = recipes[0];

export function getRecipe(id: string) {
  return recipes.find((r) => r.id === id);
}

/** All distinct cuisine/region values currently present in the catalog,
 *  sorted by recipe count (descending). Used to power the cuisine grid. */
export function getCuisines(): { name: string; count: number }[] {
  const counts = new Map<string, number>();
  for (const r of recipes) {
    if (!r.region) continue;
    counts.set(r.region, (counts.get(r.region) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count);
}

export function recipesByCuisine(cuisine: string): Recipe[] {
  return recipes.filter((r) => r.region === cuisine);
}
